# Cassandra Connection Properties
hibernate:
  ogm:
    datastore:
      provider: cassandra
      host: localhost
      keyspace: your_keyspace_name
      username: your_username
      password: your_password

# Hibernate Properties
spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
    hibernate:
      ddl-auto: update
